### ISSUE TITLE
geoDisplay crashes X server

### ISSUE THREAD

**Issue by jstrube** [iLCSoft/iLCInstall#3]
Reported here:
https://github.com/AIDASoft/DD4hep/issues/21
Running `geoDisplay` after `source /cvmfs/ilc.desy.de/sw/x86_64_gcc48_sl6/v01-17-10/init_ilcsoft.sh` crashes the X server. The fix is to run (thanks @petricm ) `find graf3d/eve/src/TEve*GL.cxx -type f -exec sed -i 's/\/\/\ fDLCache\ /fDLCache\ /g' {} \;` in ROOT and rebuild. (Or chose sane delimiters for `sed`).
Apparently, this works in the clicdp cvmfs. Would be nice if this could also be made to work in the desy repo. There's no proper /cvmfs github, so I'm reporting here. @gaede if there's a better place for reporting this, please let me know.

**Comment by petricm** [comment]
This is not a single error it's more complicated. It depends on the 

- OpenGL drivers on the server side (there are some issues with e.g. intel support on lxplus, ...)
- version of your X (e.g. on Mac XQuartz if very buggy, and as far as I know only 2.7.8 works)
- what actually you want to achieve e.g. running geoDisplay vs teveDispaly causes different problems
- your connection speed, some issues only appear on low bandwidth (caching)

The mentioned patch only addresses the teveDispaly issues. It's hard to get things working for everybody, since it very depends on the particular hardware setup and drivers.

**Comment by jstrube** [comment]
Thanks for putting this into context.
Let's take a step back for a second. What I am looking for is a program that I can install on my local machine. When somebody hands me a geometry file, I would like to be able to visualize this file.
How would I achieve this?

**Comment by petricm** [comment]
Once [this](https://github.com/osschar/root/commit/2da70f676cfce6eb396e8916d0c3c871a51e8e8c) reaches root this should be resolved, but in the meantime I cannot give you any better solution. You can tryout this commit and add to your rootrc `OpenGL.UseDisplayLists: 0`. But as a reference Belle II/basf2 also patches it's root to disable fDLCache in the externals.
